### ISSUE TITLE
Using this component: Ionic

### ISSUE THREAD

**Issue by janpio** [ionic-team/stencil-component-starter#1]
Stencil is closely related to Ionic. How about some install instructions on how to use a component build on the starter in Ionic?

**Comment by jgw96** [comment]
Hey Jan! For this use case (as you could for any framework) you could either use https://github.com/ionic-team/stencil-component-starter#script-tag or https://github.com/ionic-team/stencil-component-starter#node-modules

**Comment by janpio** [comment]
Doesn't this feel wrong? Script tag needs online connection, node modules in index.html includes it for all pages even if only needed in some obscure sub page. Or am I missing something?
