### ISSUE TITLE
Add an interfaces.d.ts file to begin with

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil-component-starter#105]
Some of the framework wrappers need manually defined interfaces exported and available for successful compilations. Adding a file at `/src/interfaces.d.ts` with the contents:

```
export * from './components';
// You can provide your custom interfaces to any consumers with this file. 
```

Can ease the integration of any given framework wrapper functions.

**Comment by splitinfinities** [comment]
Another item to consider - pointing to this new `interface.d.ts` file from within the `package.json`: https://github.com/ionic-team/stencil-component-starter/blob/master/package.json#L9 (not from the `src` directory, but from the `dist` directory)

**Comment by rwaskiewicz** [comment]
After discussing the direction of the `interface.d.ts` file in the Framework repo recently, I've decided we won't be moving forward with this. We may consider a more specialized starter in the future `npm init stencil stencil-angular my-project-name`, but would like to keep the stencil-component-starter a simpler version of getting started with Stencil for now.
