### ISSUE TITLE
Build generate dist/esm/index.js empty file

### ISSUE THREAD

**Issue by robertodavila7** [ionic-team/stencil-component-starter#109]
Hi.

I create a normal hello-world component and build it with

`npm run build`

It creates a dist folder but dist/esm/index.js  is empty so I can't export my web component to another project because /dist/index.js file points to an empty file:

`export * from './esm/index.js';`

Can somebody help me?

Stencil Version: 2.13.0

**Comment by laujonat** [comment]
same issue for us too
