### ISSUE TITLE
How to use a stencli web component in a stencil app?

### ISSUE THREAD

**Issue by jackchoumine** [ionic-team/stencil-component-starter#110]
I have  a stencil-starter app. 
I install a web component by npm : `npm i web-components-jack` then  add `import 'web-components-jack` in my `index.ts`

this web-components-jack is build by stencil 

<img width="947" alt="image" src="https://user-images.githubusercontent.com/21340150/160276788-12779618-258e-47f7-97f7-134f841f8167.png">

use a web componet in stencil componet  then get error:
```bash
 Rollup: Unresolved Import
           Could not resolve './dropdown.css?tag=my-dropdown'
           from
           ./node_modules/web-components-jack/dist/collection/components/dropdown/dropdown.js
```
i import web-components-jack by script tag in html,it works well.
how can i fix it?

**Comment by rwaskiewicz** [comment]
Hey @jackchoumine,

These types of questions are best suited to the [#technical-questions in the Stencil Slack](https://stencil-worldwide.slack.com/archives/C79EANFL7), where community members help each other out with types of questions like these.

I'm going to close this issue out, as a support question. Thanks again!
