### ISSUE TITLE
3x Terminate batch job when using ^C and N or n is ignored

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-component-starter#15]
```
C:\ae\stencil-component-starter>npm list @stencil/core
my-name@0.0.1 C:\ae\stencil-component-starter
`-- @stencil/core@0.0.6-4
```

Also here: https://github.com/ionic-team/stencil-app-starter/issues/11

Windows 10

![capture188](https://user-images.githubusercontent.com/140737/31110517-881d75e2-a7bc-11e7-92a3-dcd06836803b.png)

**Comment by jgw96** [comment]
Closing this as a duplicate of https://github.com/ionic-team/stencil-utils/issues/1
