### ISSUE TITLE
How do I specify the build path?

### ISSUE THREAD

**Issue by gbelmm** [ionic-team/stencil-component-starter#17]
How do I specify the build path?

example

stencil/my-map

 "npm run build" 

to

www/mymap

![captura de pantalla 2017-10-03 a la s 17 57 02](https://user-images.githubusercontent.com/731936/31148940-a3106e74-a864-11e7-868e-249f9af4fe01.png)

**Comment by jgw96** [comment]
Hey! Since this seems like a support issue I would recommend joining the [Stencil worldwide slack](https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjQ2MzkyMTY0MTk0LTQ4ODgzYjFjNjdkNDY3YWVhMmNlMTljMWQxNTM3Yjg0ZTIyZTM1MmU2YWE5YzNjNzE1MmQ3ZTk2NjQ1YzM5ZDM) and asking there. Thanks!
