### ISSUE TITLE
no newline ping-pong

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-component-starter#19]
I am working on Windows and git is always barking at this.

![capture192](https://user-images.githubusercontent.com/140737/31176005-288c8d7e-a8c6-11e7-86d5-11d9ec345f25.png)

![capture193](https://user-images.githubusercontent.com/140737/31176013-2ee23598-a8c6-11e7-9cbc-ebb10eba20c8.png)

**Comment by peterennis** [comment]
Fixed in this PR: https://github.com/ionic-team/stencil-component-starter/pull/13/files

**Comment by jgw96** [comment]
Merged your PR. Thanks!
