### ISSUE TITLE
spec test language error

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-component-starter#22]
Fixed in this PR #21

**Comment by jgw96** [comment]
Just merged your PR. Thanks!

**Comment by jgw96** [comment]
btw @peterennis are you on twitter? If so what is your twitter handle?

**Comment by peterennis** [comment]
@jgw96  I am a [twit](http://www.thefreedictionary.com/twit) @adaept but I have not done much with it yet :)
