### ISSUE TITLE
How to build multiple bundles?

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-component-starter#23]
```
$ npm list @stencil/core
ae-stencil-menu@0.0.1 C:\ae\ae-stencil-component-starter
`-- @stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
The system creates one bundle.
I would like to build multiple components without needing different
projects with constant editing just for setup.
There is no current scaffolding for this and I am working
toward that.
Ref: https://github.com/ionic-team/stencil-component-starter/issues/5
It is not clear if Ionic want to use Yeoman, a stencil CLI tool, or something else.

Does the system actually do this and I do not know?
Is there some guidance?
What is the future plan?

I could run a bunch of sed scripts on my current sandbox
but that only works for my case. 

**Steps to reproduce:**

Demo here: 

https://github.com/adaept/ae-stencil-component-starter/tree/aedev

![capture197](https://user-images.githubusercontent.com/140737/31311907-3a13bde0-ab6b-11e7-8470-c11102a6a479.png)

```
peter@Merry-Christmas MINGW64 /c/ae/ae-stencil-component-starter (aedev)
$ npm test

> ae-stencil-menu@0.0.1 test C:\ae\ae-stencil-component-starter
> jest --no-cache

PASS src\components\ion-my-name\ion-my-name.spec.ts
PASS src\components\my-name\my-name.spec.ts
PASS src\components\ae-stencil-menu\ae-stencil-menu.spec.ts

Test Suites: 3 passed, 3 total
Tests:       15 passed, 15 total
Snapshots:   0 total
Time:        4.338s
Ran all test suites.
```

![capture198](https://user-images.githubusercontent.com/140737/31312144-965be91a-ab70-11e7-9ae1-1b5b84ea9445.png)

**Comment by jgw96** [comment]
Hey! Here is an example of how to tell stencil to build multiple bundles https://github.com/ionic-team/ionic-stencil-hn-app/blob/master/stencil.config.js#L2. Each entry in that array will be a separate bundle when the stencil compiler runs.
