### ISSUE TITLE
stencil-app-starter and stencil-component-starter divergence

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-component-starter#24]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Here: https://github.com/ionic-team/stencil-app-starter/pull/18

I suspect this would also be relevant to the components.

Does it make sense to have something like the app scripts
that keeps these projects in sync?

**Comment by jgw96** [comment]
Hey @peterennis , so yeah this is a valid concern. Right now we just manually make sure that the repos are in sync. We could have something like we do with ionic-angular and have an app-base that the starters are built with, but that would mean that its then not as simple to get started with a stencil project (currently its just a git clone away). Any ideas on how we could do this better?

**Comment by peterennis** [comment]
See #5 

I am working on this here:
https://github.com/adaept/ae-stencil-component-starter/tree/aedev/src

Early days, but my thinking is that "generator-stencil-component"
could become "generator-stencil" and the first question would
be "Do you want to create an app or components?".

I have an interest in getting this working for scaffolding
multiple components as seen here: https://github.com/ionic-team/stencil-component-starter/issues/23

I will let you know when I get my alpha version working and you
can consider how it could align with possibly solving divergence
and maintaining simplicity.

**Comment by jgw96** [comment]
@peterennis if you aren't already, you should join our Stencil slack as I would love to know the progress on this! You can join using this link https://stencil-worldwide.herokuapp.com/ . Also, because this is not really an issue, but more of a discussion, I am going to be closing this issue for now. Thanks for using Stencil!
