### ISSUE TITLE
ENOENT: no such file or directory during npm install for @types\node

### ISSUE THREAD

**Issue by rehannawab** [ionic-team/stencil-component-starter#28]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Hello, I keep running into this error while running npm install.**

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! path C:\Rehan\Stencil\my-web-component\node_modules\.staging\@types\node-7a5f5d35
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Rehan\Stencil\my-web-component\node_modules\.staging\@types\node-7a5f5d35' -> 'C:\Rehan\Stencil\my-web-component\node_modules\@stencil\core\node_modules\@types\node'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Rehan\Stencil\my-web-component\node_modules\.staging\@types\node-7a5f5d35' -> 'C:\Rehan\Stencil\my-web-component\node_modules\@stencil\core\node_modules\@types\node'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Rehan\Stencil\my-web-component\npm-debug.log

**Comment by jgw96** [comment]
Hey @rehannawab , are you able to reproduce this with a fresh clone? Thanks!

**Comment by ntrantrinh** [comment]
I have a similar issue on fresh clone.
3077 error path /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/npm/node_modules/ansistyles
3078 error code ENOENT
3079 error errno -2
3080 error syscall rename
3081 error enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/npm/node_modules/ansistyles' -> '/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/npm/node_modules/.ansistyles.DELETE'
3082 error enoent This is related to npm not being able to find a file.

**Comment by strawberryGorilla** [comment]
Also having the same issue.

**Comment by strawberryGorilla** [comment]
Also having this issue, although in a different context.  It's causing the failure when running `npm install -g ionic cordova`

**Comment by pd-giz-dave** [comment]
I'm on Ubuntu 17.10 and Node 9.5 and see exactly the same error when doing `npm install cordova`
I notice their is an `ansi-styles` module but not an `ansistyles`. Is something stripping punctuation?

**Comment by pd-giz-dave** [comment]
Rolling back to node 7.9 did not fix it for me.

**Comment by pd-giz-dave** [comment]
Rolling back npm from 5.6 to 4.6 did fix it.

**Comment by FreddyCrugger** [comment]
Same error for me
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! path C:\Users\Ben\AppData\Roaming\npm\node_modules\phonegap\node_modules\npm\node_modules\ansistyles
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Ben\AppData\Roaming\npm\node_modules\phonegap\node_modules\npm\node_modules\ansistyles' -> 'C:\Users\Ben\AppData\Roaming\npm\node_modules\phonegap\node_modules\npm\node_modules\.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by jgw96** [comment]
Hello all! Is this only happening on Linux? I'm on node 8 on windows 10 and am not seeing this issue. Also, can you do a fresh pull of this repo and run `npm install`. I just updated this to the latest of everything so that might fix the issue your seeing.

**Comment by FreddyCrugger** [comment]
What seems to have fixed mine on Windows 10 is the use of the Node.js command prompt rather than the command prompt from Windows itself. When using the node.js CMD all my npm updated properly without this error.

**Comment by jgw96** [comment]
Hello all! As it sounds like this came down to npm being buggy and is not really a stencil issue I am going to be closing this for now. Thanks everyone!
