### ISSUE TITLE
assets folder does not exist

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-component-starter#3]
Index.html refers to favicon.ico but there is no assets folder in stencil-component-starter.

![capture169](https://user-images.githubusercontent.com/140737/30788300-d1cd80f2-a14e-11e7-83ac-41411472cf7a.png)

**Comment by siedentm** [comment]
The www directory is for testing/development purposes only as far as I understand. just get rid of the icon link.

**Comment by siedentm** [comment]
this can be closed i believe :)

**Comment by peterennis** [comment]
Done. Thanks for the reminder.
