### ISSUE TITLE
my-name -> my-component : my-name is not changed in package-lock.json

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-component-starter#30]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

my-name is not changed in package-lock.json

![capture210](https://user-images.githubusercontent.com/140737/31805553-7dddd416-b516-11e7-9446-fc97b950905b.png)

**Comment by jgw96** [comment]
Hey! I just fixed this issue. Thanks for using Stencil!
