### ISSUE TITLE
Jest: Cannot read property 'textContent' of null

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil-component-starter#37]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.8-0
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Jest testing failing with null errors. 

**Expected behavior:**
Tests function properly.

**Steps to reproduce:**

1. Clone the `stencil-component-starter`
2. Run `npm i`
3. Run `npm test`

**Related code:**
```
// No changes whatsoever
```

**Other information:**

Thanks for all the hard work.

**Comment by dimi-nk** [comment]
Caused by: https://github.com/ionic-team/stencil/issues/311

**Comment by cary-smith** [comment]
Closing in favor of https://github.com/ionic-team/stencil/issues/311
