### ISSUE TITLE
How do I update package-lock.json for a stencil component starter?

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-component-starter#4]
The file shows my-name.
I want it to show ae-stencil and fix the checksum etc.
Are there instructions for doing this?

![capture171](https://user-images.githubusercontent.com/140737/30792199-55831dc6-a16d-11e7-9372-a2862e1a9788.png)

**Comment by siedentm** [comment]
You don't have to. package-lock.json is an npm-generated and npm-managed file. If you run `npm install --save @stencil/core@next` or respectively the version you target instead of next, package-lock.json gets updated automatically.

**Comment by peterennis** [comment]
OK. I think I understand now. When I have done a few more iterations of the process it will become clearer. Thanks.
