### ISSUE TITLE
Small syntax error in docs

### ISSUE THREAD

**Issue by adriancarriger** [ionic-team/stencil-component-starter#40]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

It looks like the `<script src='node_modules/my-component/dist/mycomponent.js></script>` is missing a `'` in the `src`.

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue and a PR!
