### ISSUE TITLE
@stencil/core package

### ISSUE THREAD

**Issue by iofirag** [ionic-team/stencil-component-starter#44]
When i install my package in an angular project i have see that "@stencil/core" also installed.

why `@stencil/core` located in `dependencies` object and not in `devDependencies` object?

**package.json**
```
"dependencies": {
    "@stencil/core": "^0.6.18"
  },
  "devDependencies": {
    ...
  },
```

should be:
```
"dependencies": {
    ...
  },
  "devDependencies": {
    "@stencil/core": "^0.6.18"
  },
```

for avoiding the installation of `@stencil/core` and make it pure web-component.

**Comment by adamdbradley** [comment]
Should be fix now, thanks

**Comment by tfrijsewijk** [comment]
So is this back? When creating a new stencil project with `yarn create stencil` -> type "components" I get

```
  "dependencies": {
    "@stencil/core": "^2.0.1"
  },
```

**Comment by jdnichollsc** [comment]
@adamdbradley do you know why? thanks mate!
