### ISSUE TITLE
Use latest @stencil/core stable version

### ISSUE THREAD

**Issue by juanmiguelbesada** [ionic-team/stencil-component-starter#46]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**
Why are this package using a fixed version of stencil/core package?

I mean, ATM, current stencil/core package in devDependencies is 0.7.7 and stencil is on 0.7.18. Why not use atleast, the latest patch version (^0.7)?

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us. I just updated the starter to the latest. We have been moving very fast lately, so a little hard to keep everything up to date. I did add the `^` this time as we have stabilized, so it should be easier to keep this starter up to date in the future.
