### ISSUE TITLE
Build broken - example component not rendering in Chrome, Firefox, IE11 neither on Windows 7, Windows 10 nor on Ubuntu 17.10.1 - only on Mac

### ISSUE THREAD

**Issue by franktopel** [ionic-team/stencil-component-starter#49]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
`-- @stencil/core@0.7.7 
```

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
After fresh install starting the dev server the example component does not render. No errors in the console whatsoever, just IE11 DOM Explorer shows this message (which cannot be c&p'ed):
[IE11 DOM Explorer message](https://imgur.com/a/pnU10)

**Expected behavior:**
Expecting the example component to render.

**Steps to reproduce:**
```
git clone https://github.com/ionic-team/stencil-starter.git test
cd test
git remote rm origin
npm install
npm run build --prod
npm run serve
```

**Related code:**
This is the source generated by `npm run build --prod` (unsure if this is helpful):
```
<!DOCTYPE html><html dir="ltr" lang="en"><head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0"> <title>Stencil Component Starter</title> <script data-resources-url="/build/mycomponent/">/*! Built with http://stenciljs.com */
!function(e,t,n,r,o,i,s,c,u,l,m,d){for((e.mycomponent=e.mycomponent||{}).components=u,e.customElements||(e.$whenDefined=[],e.customElements={whenDefined:function(t){return{then:function(n){e.$whenDefined.push([t,n])}}}}),(m=u.filter(function(e){return e[2]}).map(function(e){return e[0]})).length&&((l=t.createElement("style")).innerHTML=m.join()+"{visibility:hidden}.hydrated{visibility:inherit}",l.setAttribute("data-styles",""),t.head.insertBefore(l,t.head.firstChild)),l=(m=t.querySelectorAll("script")).length-1;l>=0&&!(d=m[l]).src&&!d.hasAttribute("data-resources-url");l--);(m=d.getAttribute("data-resources-url"))&&(o=m),!o&&d.src&&(o=(m=d.src.split("/").slice(0,-1)).join("/")+(m.length?"/":"")+"mycomponent/"),l=t.createElement("script"),function(e,t,n,r){return!(t.search.indexOf("core=esm")>0)&&(!(!(t.search.indexOf("core=es5")>0||"file:"===t.protocol)&&e.customElements&&e.customElements.define&&e.fetch&&e.CSS&&e.CSS.supports&&e.CSS.supports("color","var(--c)")&&"noModule"in n)||function(e){try{return new Function('import("")'),!1}catch(e){}return!0}())}(e,e.location,l)?l.src=o+"mycomponent.jpysghnx.js":(l.src=o+"mycomponent.jvyrrdlw.js",l.setAttribute("type","module"),l.setAttribute("crossorigin",!0)),l.setAttribute("data-resources-url",o),l.setAttribute("data-namespace","mycomponent"),t.head.appendChild(l)}(window,document,0,0,0,0,0,0,[],void 0);</script> </head>
<body> <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component> <script>"serviceWorker"in navigator&&"file:"!==location.protocol&&window.addEventListener("load",function(){navigator.serviceWorker.register("/sw.js").then(function(e){console.log("service worker registered",e),e.onupdatefound=function(){var n=e.installing;n.onstatechange=function(){"installed"===n.state&&window.dispatchEvent(new Event("swUpdate"))}}}).catch(function(e){console.log("service worker error",e)})});</script> <script type="text/javascript" src="http://localhost:35729/livereload.js?snipver=1" charset="utf-8"></script>
        </body></html>
```

**Other information:**
Chrome console shows this:
[Chrome with npm run serve](https://imgur.com/a/P3tHI)

All browsers mentioned are installed with their latest stable version.

node v8.11.1
npm 5.6.0

**Comment by franktopel** [comment]
Will now try using Ubuntu 17.10.1, back in some minutes

**Comment by franktopel** [comment]
Also fails using  `npm run dev` on Chrome Version 65.0.3325.181 (Official Build) (64-Bit)/Ubuntu 17.10.1:

```
A bad HTTP response code (404) was received when fetching the script.
sw.js Failed to load resource: net::ERR_INVALID_RESPONSE
```
https://imgur.com/a/esg2g

**Comment by franktopel** [comment]
I tried going back to commit eb7989206ddc1ffed01db6c48a850591a5871ab1 which had Stencil core 0.7.6 

Fresh install of the component starter, then npm run build --prod followed by npm run serve gives me

o70a0g6k.js:2 Uncaught (in promise) SyntaxError: Unexpected token export
    at Object.<anonymous> (workbox-core.dev.js:842)
    at Generator.next (<anonymous>)
    at step (workbox-core.dev.js:14)
    at workbox-core.dev.js:25
(anonymous) @ workbox-core.dev.js:842
step @ workbox-core.dev.js:14
(anonymous) @ workbox-core.dev.js:25

[Chrome console error](https://imgur.com/a/2EGpG)

**Comment by franktopel** [comment]
Will give it a third shot on Mac at home, in about 2 hours.

**Comment by franktopel** [comment]
Next attempt is gonna be Windows 10.

**Comment by jgw96** [comment]
@franktopel so so far, this is only breaking on Ubuntu right?

**Comment by jgw96** [comment]
Just making sure im following here. Same version of Node on every machine?

**Comment by franktopel** [comment]
Node v 8.11.1 on all machines. Working only on Mac, but neither on Windows 7 nor on Ubuntu 17.10.1.

**Comment by franktopel** [comment]
Still updating Windows 10, might be only tomorrow when I can post whether it works on Windows 10.

**Comment by franktopel** [comment]
Just checked. Does not work on a freshly installed and updated Windows 10 system.

![grafik](https://user-images.githubusercontent.com/10668603/38718765-e2102184-3eee-11e8-8d46-1dc49e394034.png)

**Comment by franktopel** [comment]
This is now the third Windows machine I'm testing this, to no avail.

**Comment by franktopel** [comment]
I have just tested on another Windows 10 machine using Node v6.14.1.

**So I wasn't able to get it working on any Windows machine whatsoever.

This is a pity since I've been assigned the task to evaluate StencilJS for usage in a really large company for a migration project. Not the best start I'd say :(**

Running `npm run dev --es5` gives me

```
C:\iskv21c\webcomponents\stencil>npm run dev --es5

> my-component@0.0.1 dev C:\iskv21c\webcomponents\stencil
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

[29:59.7]  @stencil/core v0.7.7 
[29:59.7]  build, mycomponent, dev mode, started ...
[29:59.9]  compile started ...
[30:13.3]  compile finished in 13.41 s

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 14
           Duplicate identifier 'describe'.

     L15:   * A focused it

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 15
           Duplicate identifier 'fdescribe'.

     L15:   * A focused it         
     L16:   * If suites or specs are focused, only those that are focused will be executed.

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 16
           Duplicate identifier 'xdescribe'.

     L15:  * A focused it
     L16:  * If suites or specs are focused, only those that are focused will be executed.
     L17:  * @param expectation

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 25
           Duplicate identifier 'it'.

     L25:   * Mark a spec as pending, expectation results will be ignored.
     L26:   * If you call the function pending anywhere in the spec body, no matter the expectations, the spec will be marked pending.

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 34
           Duplicate identifier 'fit'.

     L33:  * Run some shared setup before each of the specs in the describe in which it is called.
     L34:  * @param action Function that contains the code to setup your specs.
     L35:  * @param timeout Custom timeout for an async beforeEach.

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 35
           Duplicate identifier 'xit'.

     L34:  * @param action Function that contains the code to setup your specs.
     L35:  * @param timeout Custom timeout for an async beforeEach.

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 50
           Duplicate identifier 'beforeEach'.

     L49:  * @param action Function that contains the code to setup your specs.
     L50:  * @param timeout Custom timeout for an async beforeAll.

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 57
           Duplicate identifier 'afterEach'.

     L56:  * Note: Be careful, sharing the teardown from a afterAll makes it easy to accidentally leak state between your specs so that they erroneou
sly pass or fail.
     L57:  * @param action Function that contains the code to teardown your specs.
     L58:  * @param timeout Custom timeout for an async afterAll

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 65
           Duplicate identifier 'beforeAll'.

     L64:   * @param spy
     L66:  declare function expect(spy: Function): jasmine.Matchers<any>;

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 73
           Duplicate identifier 'afterAll'.

     L72:  declare function expect<T>(actual: ArrayLike<T>): jasmine.ArrayLikeMatchers<T>;

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 79
           Cannot redeclare block-scoped variable 'expect'.

     L78:  declare function expect<T>(actual: T): jasmine.Matchers<T>;

[ ERROR ]  typescript: C:/iskv21c/webcomponents/node_modules/@types/jasmine/index.d.ts, line: 134
           Duplicate identifier 'clock'.

    L134:      function createSpyObj(baseName: string, methodNames: any[] | {[methodName: string]: any}): any;
    L135:      function createSpyObj<T>(baseName: string, methodNames: any[] | {[methodName: string]: any}): SpyObj<T>;

[30:13.3]  build failed, watching for changes... in 13.65 s
```

**Comment by jgw96** [comment]
Hey @franktopel , sorry about the issues you're running into, this is on me. From the errors your getting, it looks like your running an old version of Stencil. That would not surprise me as I currently have this starter set to an old version of Stencil. I am going to update this starter, double check it works locally on my machine and then I will ping you here so you can give it a go. Also, if you would like, you can join the Stencil slack https://stencil-worldwide.herokuapp.com/. I try to be available on there at all times (my username is Justin Willis). Thanks for trying out Stencil!

**Comment by jgw96** [comment]
@franktopel Alright, ive updated the starter locally and everything seems to be working on my Windows 10 machine. Going to do a few more tests and then ill push the updates.

**Comment by franktopel** [comment]
Thanks alot for your quick reaction. On 4 different windows machines I was getting 4 different behaviours - are you sure this can be fixed by updating some version? As the company I'm evaluating Stencil for comes from the Java/Swing world they are deeply rooted in Windows. Noone will even consider changing the OS here. I will try at work tomorrow and report how it goes.

**Comment by franktopel** [comment]
I just tested on Windows 7 Professional 64 bit, latest Chrome, and IE11. **It fails.**
![image](https://user-images.githubusercontent.com/10668603/38801921-67374f58-416b-11e8-92bb-e7d857c66097.png)
![image](https://user-images.githubusercontent.com/10668603/38801966-841daa0e-416b-11e8-97bb-bc49122dc1b9.png)

![image](https://user-images.githubusercontent.com/10668603/38801907-5d2320f0-416b-11e8-83d5-abe4d7374918.png)

**Comment by franktopel** [comment]
Re-tested on Ubuntu 17.10.1 / latest Chrome. # **It fails.**

![bildschirmfoto von 2018-04-16 11-52-54](https://user-images.githubusercontent.com/10668603/38802443-bdfbde2a-416c-11e8-9a3b-67d0edc71170.png)

![bildschirmfoto von 2018-04-16 11-52-18](https://user-images.githubusercontent.com/10668603/38802423-ad02df92-416c-11e8-923e-9ab2560c8b46.png)

**Comment by franktopel** [comment]
It also fails using `npm run build && npm serve` (Ubuntu 17.10.1/ latest Chrome). The element is never registered.

![bildschirmfoto von 2018-04-16 12-00-54](https://user-images.githubusercontent.com/10668603/38802962-0e5c41e2-416e-11e8-8b8e-428a0e00c073.png)

**Comment by jgw96** [comment]
@franktopel So one of our goals with Stencil is to make sure that 1. it always works everywhere and 2. we always keep breaking changes to a minimal. There were some build issues with older versions, but they had been fixed in the latest version, which is why I updated it. Debugging more today

**Comment by franktopel** [comment]
After we got it to work on a Macbook running Windows 10 in Bootcamp during a teamviewer session, I tried on tow different machines since then, one running Windows 8.1, the other running Windows 10. Both received fresh installs of Nodejs 8.11.1, **on both machines it failed silently**, meaning the build works, but the component never registers, rendering the page blank with no console errors whatsoever.

**Comment by yanis-git** [comment]
Hello, i unfortunately notice same issue on mac with following setup : 
- Node v9.2.0
- npm 5.5.1
- stencil 0.7.22 or 0.7.27

let me know if i can help

**Comment by karlito40** [comment]
I encounter the same problem on :

+ Node v10.2.1
+ npm 5.6.0
+ Mac 10.11.6
+ Chrome 67, Firefox, Safari (didn't test on edge)

 I'm not sure if it's normal but in `www/build/mycomponent/mycomponent.core.js` `App.components` is empty so `defineComponent(cmpMeta, HostElementConstructor)`is never called.

`stencil-app-starter`is not working either

**Comment by kensodemann** [comment]
I just tested this using the latest version of this starter on Mac, Linux, and Windows using both the stable and LTS versions of node. It worked in all cases, so I am going to close this.
