### ISSUE TITLE
Yeoman Generator

### ISSUE THREAD

**Issue by heyMP** [ionic-team/stencil-component-starter#5]
Not a huge deal, but if there was a yeoman generator to spin up a new stencil component template, that would be sweet.  That way yeoman can include the correct name of the component throughout the files.

**Comment by adamdbradley** [comment]
Not opposed to it, but would be great to get community help building this. Thanks

**Comment by peterennis** [comment]
Working on this in my sandbox here: https://github.com/adaept/ae-stencil-component-starter/commits/aedev

**Comment by jgw96** [comment]
Hey @peterennis , as I posted on the other issue where you mentioned this tool, feel free to ping me in Stencil Slack about this! (: Because this is not an issue and more of a discussion I am going to close this issue for now and move this conversation to Slack. Thanks!
