### ISSUE TITLE
Invalid HTML coverage report generated (wrong remapping)

### ISSUE THREAD

**Issue by semagarcia** [ionic-team/stencil-component-starter#56]
**Stencil version:** 

```
@stencil/core@0.9.1
```

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Hi. I've forked the repo and I've added a couple of methods into _MyComponent_ class. The content is irrelevant because its purpose is only to increase the length of the source. Doing so, some lines will be uncovered by the default tests included by the repo.

After that, I've executed tests with coverage flag (_jest --coverage_). When I review the HTML report generated, the lines highlighted are wrong, because remapping js->ts seems to be incorrect.

<img width="658" alt="screen shot 2018-06-11 at 00 24 43" src="https://user-images.githubusercontent.com/10792397/41207845-a0583266-6d1c-11e8-9a18-88773fbefdf8.png">

**Expected behavior:**
The couple of methods added should be highlighted as not called methods (uncovered).

**Steps to reproduce:**
To reproduce the bug you can follow the previous detailed steps or you can clone this [branch](https://github.com/semagarcia/stencil-component-starter/commits/coverage-bug). 

**Related code:**
Nothing.

**Other information:**
Other dependency versions:
```
  $> @stencil/utils@0.0.4 
  $> jest@21.2.1
```

**Comment by silverspectro** [comment]
Hello,

Is there any news on this one ?
I still have the issue into the latest `stencil-component-starter` project.

**Comment by rwaskiewicz** [comment]
Hey all 👋 

I apologize for how long it took for someone on the Stencil team to respond to this. I've tested this with the latest version of the component starter, and it appears that the sourcemaps are being generated correctly at this time. Should anyone be encountering an issue in an already established project with sourcemapping, please feel free to open a new issue. Thanks, and once again, I apologize for the lack of response.
