### ISSUE TITLE
npm installing my component looking for /build/ at root

### ISSUE THREAD

**Issue by tsaarikivi** [ionic-team/stencil-component-starter#6]
Is there possibly a bug(?) in stand-alone stencil components?
Running npm run build -> publishing to npm -> installing to my angular 4 project -> including the script:
Results in 404 not found. The component is looking for the /build/ folder. Which is ofc not in the server root because the component is installed via npm and bundled by webpack as it is included from node_modules.

Something I missed?
Or just not thought out?

Thanks!

**Comment by jgw96** [comment]
Closing this as we talked about it on the stencil worldwide slack. Thanks!
