### ISSUE TITLE
How to set styleUrls in @Component 

### ISSUE THREAD

**Issue by guochun** [ionic-team/stencil-component-starter#73]
I want to show difference theme  that according to set difference mode. 
so I wirte code that
``` js
@Component({  
  tag: "aui-button",
  styleUrls: {
    pc: "button.pc.css",
    mobile: "button.mobile.css"
  },
  shadow: true
})
```
![image](https://user-images.githubusercontent.com/16466654/58190878-020e5600-7cf0-11e9-8e7b-665b37909873.png)

then  execute  npm run start . in www  directory

![image](https://user-images.githubusercontent.com/16466654/58190927-1a7e7080-7cf0-11e9-8252-b9a146c40900.png)

finally in chrom browser I get error
![image](https://user-images.githubusercontent.com/16466654/58190996-426dd400-7cf0-11e9-9297-ad89d89e531c.png)

Thanks for help

**Comment by rwaskiewicz** [comment]
Thanks for the issue! This issue appears to be a support request. We use this issue tracker exclusively for
bug reports and feature requests. Please use our [forum](https://forum.ionicframework.com) for questions about the framework.


Thank you for using Ionic!
