### ISSUE TITLE
Change Stencil version in package.json

### ISSUE THREAD

**Issue by lcswillems** [ionic-team/stencil-component-starter#76]
Hi,

Thank you so much for Stencil!

Now Stencil One is released, you could update the package.json?

**Comment by peterennis** [comment]
Fixed here: https://github.com/ionic-team/stencil-component-starter/commit/e1ca6c00046b7579cb7b972274730367a3090992

**Comment by rwaskiewicz** [comment]
I’m going to close this issue, as it seems like the primary ask here has been addressed. Thanks again!
