### ISSUE TITLE
Explicitly add types to dependencies

### ISSUE THREAD

**Issue by hv-pul** [ionic-team/stencil-component-starter#88]
When using a fresh starter project, the dev server will run throw errors when `@types/jest` and `@types/puppeteer` are not installed.

The test script install them as dev dependencies on the first run, but this is not documented as far as I can tell.

If there was either a warning to run the test suite once or if the type-packages were part of the dev-dependencies from the beginning, this might save some initial confusion.

**Comment by rwaskiewicz** [comment]
👋 this should be resolved as of https://github.com/ionic-team/stencil-component-starter/pull/98/files. Thanks!
