### ISSUE TITLE
Setting 'hashFileNames: false' not working on all generated files

### ISSUE THREAD

**Issue by siedentm** [ionic-team/stencil-component-starter#9]
It's working as intended for the bundle files, but not for the core.js and core.pf.js, which still receive hash names. 
![screenshot_20170927_090612](https://user-images.githubusercontent.com/6476810/30900677-3196a9a6-a365-11e7-89d5-7a1f1080ef36.png)

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil#218

**Comment by jgw96** [comment]
Hey! Since this is more of an issue with the compiler and not this starter I have moved your issue to the main stencil repo. Thanks!
